export enum SqlCommandTypes {
    Select = 'Select',
    Insert = 'Insert',
    Update = 'Update',
    Delete = 'Delete',
    //Create = 'Create',
    //Drop = 'Drop',
    //Alter = 'Alter',
    //Truncate = 'Truncate',
    //Grant = 'Grant',
    //Revoke = 'Revoke',
    //Call = 'Call',
    //Declare = 'Declare',
    //Set = 'Set',
    //Begin = 'Begin',
    //Commit = 'Commit',
    //Rollback = 'Rollback',
    //Savepoint = 'Savepoint',
    //Release = 'Release',
}