export enum SqlOperators {
    equals = '=',
    notEquals = '<>',
    greaterThan = '>',
    lessThan = '<',
    greaterThanOrEqual = '>=',
    lessThanOrEqual = '<=',
    like = 'LIKE',
    notLike = 'NOT LIKE',
    //in = 'IN',
    //notIn = 'NOT IN',
    //between = 'BETWEEN',
    //notBetween = 'NOT BETWEEN',
    //isNull = 'IS NULL',
    //isNotNull = 'IS NOT NULL',
    //any = 'ANY',
    //all = 'ALL',
    //exists = 'EXISTS',
    //notExists = 'NOT EXISTS',
    //distinct = 'DISTINCT',    
}